x=raw_input()
a,b=x.split()
print (a**b)x=raw_input()
a,b=x.split()
print (a**b)x=raw_input()
a,b=x.split()
print (a**b)x=raw_input()
a,b=x.split()
print (a**b)x=raw_input()
a,b=x.split()
print (a**b)x=raw_input()
a,b=x.split()
print (a**b)x=raw_input()
a,b=x.split()
print (a**b)x=raw_input()
a,b=x.split()
print (a**b)
